[build]
builder = "dockerfile"
dockerfilePath = "apps/server/Dockerfile"

[deploy]
startCommand = "node apps/server/dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
